### PR TITLE
feat: enable semantic commits

### PR DESCRIPTION
**Pull request by jpnurmi**
https://docs.renovatebot.com/semantic-commits/

NOTE: This is just the org-wide default. Individual projects may still choose to disable semantic commits by extending `semanticCommitsDisabled` should they prefer so. :)

### CODE REVIEW

**Review by CarlosNihelton — APPROVED** [review]
LGTM 👍🏽

**Comment by jpnurmi** [comment]
@Feichtmeier are you using the Renovate bot in any projects?

**Comment by Feichtmeier** [comment]
> @Feichtmeier are you using the Renovate bot in any projects?

I think I activated it in musicpod once but this is on hold until the libs I depend on are updated to dart3

**Review by Feichtmeier — APPROVED** [review]

**Comment by jpnurmi** [comment]
@Feichtmeier Is it ok to change the Renovate bot to use semantic aka. conventional commits by default?

Before:
> Update dependency foo to ^1.2.3

After:
> chore(deps): update dependency foo to ^1.2.3

You can still disable the feature in `renovate.json` for specific repos if you prefer:
```diff
diff --git a/renovate.json b/renovate.json
index f72b31d..55ad97b 100644
--- a/renovate.json
+++ b/renovate.json
@@ -1,6 +1,7 @@
 {
   "$schema": "https://docs.renovatebot.com/renovate-schema.json",
   "extends": [
-    "local>ubuntu-flutter-community/renovate-config"
+    "local>ubuntu-flutter-community/renovate-config",
+    ":semanticCommitsDisabled"
   ]
 }
```

**Comment by Feichtmeier** [comment]
Yes stuff is really cool. I'll read it up to make the correct commits

**Pull request merged**
